version: v1.0
name: Deployment to staging
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804

blocks:
  - name: "Install and cache deps"
    task:
      env_vars:
        - name: BUNDLE_PATH
          value: vendor/bundle
      jobs:
      - name: "Install and cache deps"
        commands:
          - echo "test"
